import React from "react";
import Head from "next/head";
import { Patient } from "../types/patients";

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/patients");
  const data = await res.json();
  return {
    props: {
      patients: data.patients,
    },
  };
}

type HomeProps = {
  patients: Patient[];
};

export default function Home({ patients }: HomeProps): JSX.Element {
  return (
    <>
      <Head>
        <title>Stitch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Patients</h1>
      </header>
      <main>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>ID</th>
              <th>Date of birth</th>
              <th>Registration date</th>
            </tr>
          </thead>
          <tbody>
            {patients.map((patient) => (
              <tr key={patient.id}>
                <td>{`${patient.firstName} ${patient.lastName}`}</td>
                <td>{patient.id}</td>
                <td>{patient.dateOfBirth}</td>
                <td>{patient.dateOfRegistration}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </>
  );
}
